version: '3.6'

services:
  ngixn:
    image: nginx:latest
    volumes:
      - ./docker/nginx/vhosts:/etc/nginx/templates
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public_html:/var/www/html
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
      NGINX_ROOT: /var/www/html
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: '.conf'
      NGINX_HOST: ${APP_DOMAIN}
      NGINX_APP: ${APP_NAME}
    networks:
      - localserver

  db:
    image: mysql:5.7
    container_name: '${APP_NAME}_db'
    restart: 'always'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/logs/mysql:/var/log/mysql
      - ./docker/db/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - localserver

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${APP_NAME}_pma'
    restart: 'always'
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
      - site
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - localserver

  site:
    container_name: ${APP_NAME}
    build: ./docker/php
    restart: 'always'
    volumes:
      - ./public_html:/var/www/html
      - ./docker/php/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${APP_PORT}:80"
    networks:
      - localserver

  composer:
    container_name: ${APP_NAME}_composer
    image: composer:latest
    volumes:
      - .:/var/www/
    networks:
      - localserver

networks:
  localserver:
    # external: true
