version: "3.8"

services:
  apache:
    container_name: ${PROJECT_NAME}_apache
    restart: always
    user: root
    ports:
      - ${PHP_PORT}:80
    build:
      context: ./docker/apache
      args:
        VER_PHP: ${PHP_VER}
    volumes:
      - ./:/var/www/

  db:
    image: mysql:${MYSQL_VER}
    container_name: ${PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
